# nginx.conf
server {
  listen 80;
  server_name localhost;

  # Racine du site (où les fichiers ont été copiés)
  root /usr/share/nginx/html;
  index index.html;

  # Essayer de servir le fichier demandé.
  # S'il n'existe pas, essayer de servir un dossier.
  # Si ça échoue, renvoyer sur /index.html pour que le routeur côté client gère la route.
  location / {
    try_files $uri $uri/ /index.html;
  }

  # Optionnel : Ajout de headers pour une meilleure gestion du cache
  location ~* \.(?:css|js|woff2|gif|ico|jpg|jpeg|png|svg|webp)$ {
    expires 1y;
    add_header Cache-Control "public, immutable";
  }
}